### ISSUE TITLE
Breaks if 2FA is enabled for github

### ISSUE THREAD

**Issue by cpakman** [osxc/legacy-boot#10]
the only response I get from this script is that 'authentication failed'

**Comment by rricard** [comment]
Well, that's weird given that the script doesn't write in the repos ...

**Comment by cpakman** [comment]
sorry, I wasn't being detailed enough - I have xc-custom cloned as a private repo, which requires auth to clone. In that case, I think it may be github that doesn't support 2fa via CLI. Feel free to close this.

**Comment by rricard** [comment]
Yeah but that raises another issue I think. Cloning repos with http is bad, I should think of something to get it with ssh.
