### ISSUE TITLE
${should_install_ansible} specific issues

### ISSUE THREAD

**Issue by arubdesu** [osxc/legacy-boot#4]
- easy_install doesn't need -E for pip
- only CFLAGS are needed for pip to install ansible(e.g., this works in a virtualenv, as per [this post](http://macops.ca/building-native-extensions-since-llvm-5-1/):
  `CFLAGS="-Wunused-command-line-argument-hard-error-in-future" pip install ansible`
- sudo is also unnecessary for ansible when using a virtualenv(which osxc doesn't take into account in general, I know)
- instead of $latest, appending @1.6.0 to the git URL would specify the 'stable/release' version that's known to work with osxc, although I understand we think all future versions will support the current functionality

**Comment by rricard** [comment]
Thanks ! You should open a pull-request. But for now, I want to let virtalenv aside and use the system's pip ... But for the rest, go on ! You're right !

**Comment by arubdesu** [comment]
Closing due to old age ;)
