### ISSUE TITLE
every other little detail 😛

### ISSUE THREAD

**Issue by arubdesu** [osxc/legacy-boot#5]
- Naming aside, (some people call the place they store repo's 'dev',) it is generally a bad practice (even if plenty of sync services and others do it) to place a folder at the root of the users home and assume a single-user system. Proper permissions are often not set by those services, so if we're at the root of the home folder, verifying a /bin/chmod 700 would be recommended
- Variable names alone could be clearer about intent/purpose - comments would definitely help to explain, `# Git remote path to osxc-maintained roles` for CM_REMOTE, I personally find it weird to specify where the git repo happens to be hosted as part of the project working directory path, but that's just me
- And most importantly, Homebrew tests for the most likely receipts left behind by an Xcode dev tools install, a la the code [here](https://github.com/Homebrew/homebrew/blob/208f963cf2ab593973200b185a107bbb305b25d0/Library/Homebrew/os/mac/xcode.rb#L147-L150) - it would be best to follow suit

I'll cook up a PR to discuss this with working code sooner rather than later

**Comment by arubdesu** [comment]
Also, re: Xcode CLI tools in particular, 10.9 seems to be an intended requirement since the GUI install only works on Mavs, let's use [this silent way](https://github.com/timsutton/osx-vm-templates/blob/master/scripts/xcode-cli-tools.sh) that works on 10.7+

**Comment by rricard** [comment]
Solved by #6.
